### ISSUE TITLE
Create a default version of SECURITY file

### ISSUE THREAD

**Issue by sgort** [MinBZK/Open-Source-Program-Office#11]
See the NCSC [Coordinated Vulnerability Disclosure: the Guideline](https://english.ncsc.nl/publications/publications/2019/juni/01/coordinated-vulnerability-disclosure-the-guideline)

**Comment by sgort** [comment]
Relates to https://github.com/MinBZK/regels.overheid.nl/issues/132

**Comment by confiks** [comment]
Consider adding a `.github` repository that hosts these files. Github will automatically reference these files in every repository. For an example, see https://github.com/minvws/.github.

Applicable to #14, #5 and #4 as well.

**Comment by sgort** [comment]
Appreciated! I am in preparation to do just that.

**Comment by sgort** [comment]
File has been committed. Where necessary, we will change "MinBZK/CIO-office github security response" afterwards.
